# -*- coding: utf-8 -*-
"""Final_AA_prsg_demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCQBNXjYua2eVqNllhiMzCNXLfLB47HE
"""


#from flask import Flask 

#app = Flask(__name__) 


import os
from flask import Flask, render_template, request
import joblib
from werkzeug.utils import secure_filename
import pandas as pd
import numpy as np
app=Flask(__name__)
'''
@app.route('/test')


def test():
    return "Flask is being used for development"
'''

#load model_prediction
#We can load model here such that it will not be loaded again if the page refreshes, iproves the performance
from tensorflow.keras.models import load_model
import string
import pandas as pd
import numpy as np

model = load_model('DEMO-PRSG/30_real_user_weight.h5')
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.classes_ = np.load('DEMO-PRSG/classes.npy',allow_pickle=True)

def create_vocab_set():
    alphabet = (list(string.ascii_lowercase) + list(string.digits) +
                list(string.punctuation) + ['\n'] + [' '] )
    vocab_size = len(alphabet)
    check = set(alphabet)

    vocab = {}
    reverse_vocab = {}
    for ix, t in enumerate(alphabet):
        vocab[t] = ix
        reverse_vocab[ix] = t

    return vocab, reverse_vocab, vocab_size, check

maxlen = 140
vocab, reverse_vocab, vocab_size, check =create_vocab_set()

def encode_data(x, maxlen, vocab, vocab_size, check):

    input_data = np.zeros((len(x), maxlen, vocab_size))
    for dix, sent in enumerate(x):
        counter = 0
        sent_array = np.zeros((maxlen, vocab_size))
        chars = list(sent.lower())
        for c in chars:
            if counter >= maxlen:
                pass
            else:
                char_array = np.zeros(vocab_size, dtype=np.int)
                if c in check:
                    ix = vocab[c]
                    char_array[ix] = 1
                sent_array[counter, :] = char_array
                counter += 1
        input_data[dix, :, :] = sent_array

    return input_data


@app.route('/')


def home():
    return render_template('Home_AA_new.html')

@app.route("/",methods=['GET','POST'])


def predict():
    if request.method == 'POST':
      files = request.files.getlist("file")
      name=[]

      for file in files:
        filename = secure_filename(file.filename)
        file.save(os.path.join("uploads2",filename))
        name.append(filename)
      print(name)
      typr_here=pd.DataFrame(name)
    
      typr_here = encode_data(name, maxlen, vocab, vocab_size, check)
      y_pred = model.predict(typr_here)
      y_pred=pd.DataFrame(y_pred)
      y_pred=y_pred.eq(y_pred.where(y_pred != 0).max(1), axis=0).astype(int)
      y_pred=y_pred.iloc[:,:].values
      result=[]
      for i in range(0,len(y_pred)):
          for j in range(0,len(y_pred[0])):
              if(y_pred[i][j]==1):
                result.append(j)
              
      author=encoder.inverse_transform(result)
       
            
        
    return render_template('predict_AA_new.html', prediction=author[0])

if __name__=="__main__":
    app.run()


#@app.route("/") 
#def home(): 
#	return "<h1>GFG is great platform to learn</h1>"
	
#app.run()



